# Build settings
[build]
  publish = "public"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to ensure proper routing
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 